apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: s3-fuse-flex-volume-deployer
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: s3-fuse-flex-volume-deployer
      labels:
        app: s3-fuse-flex-volume-deployer
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: s3-fuse-flex-volume-deploy
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-plugindir
            - mountPath: /hostbin
              name: flexvolume-usrlocalbin
      volumes:
        - name: flexvolume-plugindir
          hostPath:
            path: {{ .Values.flexVolume.pluginDir | quote }}
        - name: flexvolume-usrlocalbin
          hostPath:
            path: '/usr/local/bin'
