apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: s3-fuse-flex-volume-deployer
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: s3-fuse-flex-volume-deployer
      labels:
        app: s3-fuse-flex-volume-deployer
    spec:
      initContainers:
        - name: install-host-deps
          image: busybox:latest
          imagePullPolicy: Always
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /rootfs
              name: rootfs
            - mountPath: /usr/local/src
              name: install_host_deps_script
          command:
            - bash
            - /usr/local/src/install_deps.sh
        - name: s3-flex-volume-drivers-deploy
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-plugindir
            - mountPath: /hostbin
              name: flexvolume-usrlocalbin
      containers:
        - name: pause
          image: gcr.io/google-containers/pause
      volumes:
        - name: flexvolume-plugindir
          hostPath:
            path: {{ .Values.flexVolume.pluginDir | quote }}
        - name: flexvolume-usrlocalbin
          hostPath:
            path: '/usr/local/bin'
        - name: rootfs
          hostPath:
            path: /
            type: Directory
        - name: install_host_deps_script
          ConfigMap:
            name: fuse_install_deps_script
