apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nfs-flex-volume-deployer
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: nfs-flex-volume-deployer
      labels:
        app: nfs-flex-volume-deployer
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: nfx-flex-volume-deploy
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-plugindir
      volumes:
        - name: flexvolume-plugindir
          hostPath:
            path: {{ .Values.flexVolume.pluginDir | quote }}
